server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booking_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 159357bapD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    com.moviebooking: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    root: INFO