# Application Configuration
spring:
  application:
    name: auction-product-management

  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/auction_system_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 159357bapD  # Thay bằng password MySQL của bạn
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Sử dụng 'update' cho MySQL thay vì 'create-drop'
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    # BẬT open-in-view để tránh LazyInitializationException
    open-in-view: true

  # Thymeleaf Configuration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  # Static Resources
  web:
    resources:
      static-locations: classpath:/static/

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  level:
    com.moviebooking: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    root: INFO